name: JobPortal
description: A Job Portal By Shubham Naik.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  toast: ^0.1.4
  flutter_multiselect: 0.4.0
  flutter_spinkit: ^4.1.1+1
  simple_animations: ^1.3.3
  fluttertoast: ^3.1.3
  flutter_signin_button: ^1.0.0
  google_sign_in: ^4.1.1
  mdi: ^1.0.1
  flutter_slidable: ^0.5.4
  image_picker: ^0.6.3+4
  mime: ^0.9.6+3


  #shivam's dependencies
  datetime_picker_formfield: ^1.0.0
  curved_navigation_bar: ^0.3.2
  flutter_country_picker: ^0.1.6
  restcountries: ^0.0.2

  flutter_svg: ^0.17.1
  passwordfield: ^0.0.5
  badges: ^1.1.0
  kf_drawer: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/locale/localization_en.json
    - assets/locale/localization_hi.json
    - assets/locale/localization_mr.json
    - assets/

